# @author DieFriiks / CustomCraftDev / undeaD_D
# @link www.custom-craft.de
# @github https://github.com/CustomCraftDev/tpjail

debug: false
nopermission-msg: 'You shall not pass'
jail-location:
  worldname: world
  x: 0.0
  y: 100.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
