name: TpJail
main: tpjail.TpJail
version: 1.0
authors: [DieFriiks, CustomCraftDev, undeaD_D]
databse: false
commands:
  tpjail:
    usage: /<command> <set/reload/disable/reset>
    description: set/reload/reset/disable tpjail plugin
permissions:
  tpjail.active:
    description: teleports you to jail on login/death
  tpjail.set:
    description: sets the new jail location
  tpjail.*:
    description: grants every permission from tpjail
    children:
      tpjail.set: true
      tpjail.reload: true
      tpjail.reset: true
      tpjail.disable: true
  tpjail.reload:
    description: reload tpjail at runtime
  tpjail.reset:
    description: reset tpjail config at runtime and reload after
  tpjail.disable:
    description: disables tpjail at runtime  
